### ISSUE TITLE
I have suggestions of changes to be made to the README.md

### ISSUE THREAD

**Issue by syspentarc** [Rohitesh-Kumar-Jain/CowWatchDogs#6]
I went through the documentation after I came across Issue #3, and found a markdown error on [README.md](https://github.com/Rohitesh-Kumar-Jain/CowWatchDogs/commit/0f54dfe7a2a5bd1500d97df603c3225150745327#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). I don't know if it was intentional or not, but here's my suggestion to fix it. I also found some spelling errors that need to be fixed.

###  I propose:
```diff
# Cow Watch Dogs

- This is a non for profit project aimed to protect cows worldwide, I aim to create a web app, which helps us to find 
- keeper for stray Cow and animals, so that they can be protected, and an aim to provide medical facilites to stray 
+ This is a non for profit project aimed to protect cows worldwide, I aim to create a web app, which helps us find 
+ keeper for stray Cow and animals, so that they can be protected, and an aim to provide medical facilities to stray 
animals. 

- ##Join My mission: 
+ ## Join My mission:
Contribute in the form of documentation. 

Tech Stack:
* Flask
* Javascript
* CSS
* HTML
* Python
```

### This is how it would look like:

# Cow Watch Dogs

This is a non for profit project aimed to protect cows worldwide, I aim to create a web app, which helps us find 
keeper for stray Cow and animals, so that they can be protected, and an aim to provide medical facilities to stray 
animals. 

## Join My mission: 
Contribute in the form of documentation. 

Tech Stack:
* Flask
* Javascript
* CSS
* HTML
* Python

`Note: Javascript could be changed to JavaScript. As far as I know it's correct either way, but some could argue that it could be counted as an error.`

**Comment by Rohitesh-Kumar-Jain** [comment]
Hi,

I think this is a good introduction, well done!

Can I ask you more thing?
I would be glad if you may raise PR for these enhancements. (I can help you create a PR if you are new to Github and need help in creating one) 

Best,
Rohitesh

**Comment by syspentarc** [comment]
Thank you! I haven't done any pool requests yet, I'd appreciate if you could help me with it.

**Comment by syspentarc** [comment]
Thank you! I haven't done any pool requests yet, I'd appreciate if you could help me with it. # @Rohitesh-Kumar-Jain

**Comment by syspentarc** [comment]
What do I do after forking the repo?

**Comment by Rohitesh-Kumar-Jain** [comment]
After forking the repo:
Open your terminal and then:

$ git clone https://github.com/syspentarc/CowWatchDogs.git

after making a local copy, open the readme file in a text editor or in an IDE.
Do the required changes, and after doing the changes, go back to your terminal and run these commands. 

$ git status  // This command will show you files in the working directory.

(At this stage you can also see what changes you have made, by running the "$ git diff" command. )
after that, add your files using 

$git add <file_name>
or you can add all the file names using $ git add .

Commit those changes 
$ git commit -m"Commit message"

and then finally push those changes 

$ git push origin <branchname>

**Comment by syspentarc** [comment]
Do you have any recommendations on how to come up with the names for the branches?

**Comment by Rohitesh-Kumar-Jain** [comment]
Just follow the convention of the repository, like some repositories follow CamleCase, lowerCamelCase, SNAKE_CASE, etc. 
It's not necessary to make a branch in order to raise a PR for this Repo, you can raise a PR from the main branch also.

**Comment by syspentarc** [comment]
I kind of tried to follow the same I did as a test on the first-contributions repo. I wasn't sure about the name, but ended up using doc-changes as the branch name.

I've already committed the changes and raised the pr.

**Comment by Rohitesh-Kumar-Jain** [comment]
Thanks I have merged your PR.

**Comment by syspentarc** [comment]
No problem, I'm glad I could help. This is my first official contribution, I'm just really glad I was able to contribute (quite difficult to find the first contributions honestly). Thanks!

**Comment by Rohitesh-Kumar-Jain** [comment]
I was in a similar situation 6-7 months back, I know it is difficult to understand git-flow and commands. But with time, you will start remembering basic commands.
